# Generated by Django 4.2.10 on 2024-07-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncellenme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
            ],
        ),
    ]
