# Generated by Django 4.2.10 on 2024-07-04 20:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Haber', 'verbose_name_plural': 'Haberler'},
        ),
        migrations.AddField(
            model_name='news',
            name='news_category',
            field=models.CharField(choices=[('SİYASİ', 'Siyasi'), ('EKONOMİ', 'Ekonomi')], default='SİYASİ', max_length=50, verbose_name='Haberin Kategorisi'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Boş içerik'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.FileField(default=1, upload_to='NewsImages/', verbose_name='Haber Resmi'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_title',
            field=models.CharField(default=1, max_length=200, verbose_name='Haber Başlığı'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='Haberler silindi mi silinmedi mi?', verbose_name='Silindi mi?'),
        ),
    ]
