# Generated by Django 4.2.10 on 2024-07-04 20:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_news_news_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_category',
            field=models.CharField(choices=[('SİYASİ', 'Siyasi'), ('EKONOMİ', 'Ekonomi')], max_length=50, verbose_name='Haberin Kategorisi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.FileField(upload_to='NewsImages/', verbose_name='Haber Resmi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(max_length=200, verbose_name='Haber Başlığı'),
        ),
    ]
