# Generated by Django 3.2.25 on 2024-07-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_front',
            field=models.TextField(default=False),
        ),
    ]
