# Generated by Django 3.2.25 on 2024-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_categories_remove_news_news_category_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_front',
            field=models.TextField(default=''),
        ),
    ]
