# Generated by Django 3.2.25 on 2024-07-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_reader',
            field=models.BooleanField(default=False),
        ),
    ]
