# Generated by Django 3.2.25 on 2024-07-08 14:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_customer_is_reader'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Reader',
        ),
    ]
