# Generated by Django 4.2.8 on 2024-07-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
