# Generated by Django 4.2.10 on 2024-07-10 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0007_alter_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_about',
            field=models.CharField(default='', max_length=100, verbose_name='Yazar Hakkında'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readers', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
